#!/bin/ksh

# {{ ansible_managed }}

datadir="{{ rw_home }}"

env="GEM_HOME=${datadir} RACK_ENV=production PATH=$PATH:$GEM_HOME/rb/bin"
daemon="/usr/local/bin/bundle24 exec rackup -p {{ rw_port }} config.ru"
daemon_user="{{ rw_user }}"

. /etc/rc.d/rc.subr

rc_start() {
	${rcexec} "env ${env} ${daemon}"
}

pexp="ruby24 {{ rw_home }}/rb/bin/rackup -p {{ rw_port }} config.ru"

rc_reload=NO
rc_bg=YES

rc_cmd $1
